### ISSUE TITLE
KeyError: 'Zenodo record does not contain a related identifier with isSupplementTo relation'

### ISSUE THREAD

**Issue by egpbos** [citation-file-format/doi2cff#2]
* Release 2 cff version: latest at this moment
* Python version: 3.6
* Operating System: macOS

### Description

I just created a [new entry on Zenodo](https://doi.org/10.5281/zenodo.1189196), but it doesn't work with release2cff.

### What I Did

```sh
$ release2cff init https://doi.org/10.5281/zenodo.1189196
Traceback (most recent call last):
  File "/Users/pbos/sw/miniconda3/bin/release2cff", line 11, in <module>
    load_entry_point('release2cff==1.0.0', 'console_scripts', 'release2cff')()
  File "/Users/pbos/sw/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pbos/sw/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/pbos/sw/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pbos/sw/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pbos/sw/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/pbos/sw/miniconda3/lib/python3.6/site-packages/release2cff/cli.py", line 54, in init
    tagurl = tagurl_of_zenodo(zenodo_record)
  File "/Users/pbos/sw/miniconda3/lib/python3.6/site-packages/release2cff/cli.py", line 110, in tagurl_of_zenodo
    raise KeyError('Zenodo record does not contain a related identifier with isSupplementTo relation ')
KeyError: 'Zenodo record does not contain a related identifier with isSupplementTo relation '
```

**Comment by sverhoeven** [comment]
The command works for GitHub releases which generate a Zenodo DOI entry. The DOI you supplied is a Zenodo conference paper entry and not a entry based on a GitHub release. 

So it is outside the scope of the current implementation, but I will accept a Pull Request which implements it.

**Comment by egpbos** [comment]
Ok, thanks for the clarification.
