### ISSUE TITLE
No isSupplementTo relation

### ISSUE THREAD

**Issue by hepcat72** [citation-file-format/doi2cff#8]
* DOI 2 cff version: 1.0.0
* Python version: tried 2.7.12 & 3.5.2
* Operating System: ubuntu

### Description

Tried creating a .cff file using a DOI.  I couldn't get doi2cff to install on my mac, so I was trying on an ubuntu virtualbox.

### What I Did

```
>doi2cff init https://doi.org/10.5281/zenodo.1303402
Traceback (most recent call last):
  File "/home/robleach/.local/bin/doi2cff", line 9, in <module>
    load_entry_point('doi2cff==1.0.0', 'console_scripts', 'doi2cff')()
  File "/home/robleach/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/robleach/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/robleach/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/robleach/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/robleach/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/robleach/.local/lib/python3.5/site-packages/doi2cff/cli.py", line 65, in init
    tagurl = tagurl_of_zenodo(zenodo_record)
  File "/home/robleach/.local/lib/python3.5/site-packages/doi2cff/cli.py", line 124, in tagurl_of_zenodo
    raise KeyError('Zenodo record does not contain a related identifier with isSupplementTo relation ')
KeyError: 'Zenodo record does not contain a related identifier with isSupplementTo relation '
```

**Comment by sverhoeven** [comment]
Sorry, to hear that you could not get it working on OSX.
On Travis-CI a [build on OSX](https://travis-ci.org/citation-file-format/doi2cff/jobs/399940643) was included. It uses [miniconda](https://conda.io/miniconda.html), maybe this allows helps you install it aswell.

The error you get is because the Zenodo DOI you supplied is not generated by a GitHub release.
At the moment `doi2cff` can only generated cff files from Zenodo entries which where generated by a GitHub release.

The error should be improved so it is clear the doi does not contain GitHub meta data.

**Comment by jspaaks** [comment]
Just to clarify: Stefan is referring to the fact that at the moment doi2cff can generate CITATION.cff files for DOIs that result from the GitHub-Zenodo integration (https://guides.github.com/activities/citable-code/).
